usermodel/userapp/urls.py
from django.urls import path
from userapp import views

app_name='userapp'

urlpatterns=[
    path('register/',views.register,name="register"),
    path('user_login/',views.user_login,name="login")
]

usermodel/usermodel/urls.py
from django.contrib import admin
from django.urls import path,include
from userapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('userapp/',include('userapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('admin/', admin.site.urls),
]

usermodel/userapp/models.py
from turtle import mode
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    profile_url=models.URLField(blank=True)

    profile_img=models.ImageField(upload_to='profilepics',blank=True)

usermodel/userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from userapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields=('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model=UserProfileInfo
        fields=('profile_url','profile_img')

usermodel/userapp/views.py
# from operator import imod
from django.urls import reverse
from xml.dom.domreg import registered
from django.http import HttpResponseRedirect,HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from userapp.forms import UserForm,UserProfileInfoForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,"index.html")

def register(request):

    registered=False

    if request.method =='POST':
        user_form=UserForm(request.POST)
        profile_form=UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():#this is for validating the form
            user=user_form.save() # we are using another variablt to use the form 
            user.set_password(user.password)#we are taking the password form registerd html
            user.save()# we are saving the variable that contains user_form

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profilepics' in request.FILES:
                profile.profilepics=request.FILES['profilepics']
            
            profile.save()

            registered=True
        
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,"register.html",{'user_form':user_form,
                                           'profile_form':profile_form,
                                            'registered':registered})


def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('user is not acctive')
        else:
            return HttpResponse('invalid cred')
    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

usermodel/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>
<body>
    <div class="container"> 
         <nav class="navbar navbar-dark bglight">
                <div class="jumbotron"> 
                    <ul class="nav navbar"> 
                         <li class="navbar-brand">
                            <a class ="nav-link" href="{% url 'index' %}" >HOME </a>
                         </li>
                         <li>
                             <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
                         </li>
                         <li>
                            <a class="nav-link" href="{% url 'userapp:register' %}">Registeration</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li>
                            <a class="nav-link" href="{% url 'logout' %}">logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a class="nav-link" href="{% url 'userapp:login' %}">login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
         </nav>
    </div>


    <div class="container">

        {% block content %}


        {% endblock %}

    </div>

</body>
</html>

usermodel/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>
        Home page...
    </h1>
</div>

{% endblock %}

usermodel/templates/login.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="jumbotorn">
    <h1> login page</h1>
    <form action="{% url 'userapp:login' %}" method="Post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="enter your name">

        <label for="username">Password</label>
        <input type="password" name="password" placeholder="enter your Password">

        <input type="submit" class="btn btn-primary" value="Login">
    </form> 
</div>
</div>
{% endblock %}

usermodel/templates/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    {% if registered %}
        <h1>
            Thank you for registeraation..!!!>
        </h1>
    {% else %}
    
    <h1> please register here...</h1>
    <h3> fill the below form</h3>

    
    <form encrypt="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type="submit" class="btn btn-primary" value="Register/">
    </form>
    {% endif %}
</div>
{% endblock %}