school/school/urls.py
from django.contrib import admin
from django.urls import path,include
from schoolapp import views
urlpatterns = [
    
    path('',views.IndexView.as_view(),name='index'),
    path('schoolapp/',include('schoolapp.urls')),
    path('admin/', admin.site.urls),
]

school/schoolapp/urls.py
from django.urls import path 
from schoolapp.views import SchoolCreateView, SchoolListView
from . import views

app_name = 'schoolapp'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailsView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update')

]

school/schoolapp/models.py
from django.db import models
from django.forms import CharField
from django.urls import reverse

# Create your models here.
#models represtns tables here school and student are the tables
class school(models.Model):
    name_of_the_school = models.CharField(max_length=250)
    prinicipal = models.CharField(max_length=100)
    address = models.CharField(max_length=300)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('schoolapp:detail',kwargs={'pk':self.pk})

#create one more model with name of student
class student(models.Model):
    name = models.CharField(max_length=100)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(school,related_name='student',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

school/schoolapp/views.py
# from multiprocessing import get_context
from django.shortcuts import render
from . import models
from telnetlib import DET
from django.views.generic import ListView,DetailView,TemplateView,CreateView,UpdateView,DeleteView

# Create your views here.
# def index(request):
#     return render(request,'index.html')
class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    #Here the schools name we have to give the same name in school_list.html inside for loop
    context_object_name = 'schools'
    model = models.school

class SchoolDetailsView(DetailView):
    context_object_name = 'school_detail'
    model = models.school
    template_name = 'schoolapp/school_detail.html'

class SchoolCreateView(CreateView):
    fields=('name_of_the_school','prinicipal','adress')
    model=models.school

class SchoolUpdateView(UpdateView):
    fields=('name_of_the_school','prinicipal')
    model=models.school 

class SchoolDeleteView(DeleteView):
    fields=('name_of_the_school','prinicipal')
    model=models.school 

school/schoolapp/templates/schoolapp/basic_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD operations</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-dark bg-dark">
            <div class="container">
                <ul class="nav navbar">
                    <li>
                        <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> "nbsp&"
                    </li>
                    <br>
                    <li>
                        <a class="navbar-link" href="{% url 'schoolapp:list' %}">Schools</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

school/schoolapp/templates/schoolapp/school_delete.html
{% extends 'schoolapp/basic_base.html' %}

{% block content %}
<div class="container">
        <div class="jumbotron">

        </div>
</div>

{% end block %}

school/schoolapp/templates/schoolapp/school_detail.html
{% extends 'schoolapp/basic_base.html' %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>Here is the school details</h1>
        <h4>Name: {{ school_detail.name_of_the_school }}</h4>
        <h4>Principal: {{ school_detail.prinicipal }}</h4>
        <h4>Address: {{ school_detail.address }}</h4>

        <h3>Students details in the school</h3>
        {% for student in school_details.students.all %}
             <h5>name is {{ student.name }} and he is {{ student.age }} years old</h5>
        {% endfor %}
    </div>
</div>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'schoolapp:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

school/schoolapp/templates/schoolapp/school_form.html
{% extends 'schoolapp/basic_base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        {% if not form.instance.pk %}
            Create school
        {% else %}
            Update school
        {% endif %}  
        
        <form method="POST">
            {% csrf_token %}
            {{  form.as_p }}

            <input type="submit" class="btn btn-primary" value="create">
        </form>
    </div>

</div>
{% endblock %}

school/schoolapp/templates/schoolapp/school_list.html
{% extends 'schoolapp/basic_base.html' %}

{% block content %}

<div class="container">
    <h1>Here is the list of  schools</h1>
    <!-- Here this schools is coming from views.py in that class name Schoollistview -->
    <ol>
    {% for school in schools %}
         <li><a href="{{ school.id }}">{{ school.name_of_the_school }}</a></li>
    {% endfor %}  
    </ol>  
</div>
{% endblock %}

school/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD operations</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-dark bg-dark">
            <div class="container">
                <ul class="nav navbar">
                    <li>
                        <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li>
                        <a class="navbar-link" href="{% url 'schoolapp:list' %}">Schools</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

school/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>Home page</h1>

    </div>
</div>
{% endblock %}

school/templates/school.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ol>
        <li>Highway English School</li>
        <li>Filters Cafe International School</li>
        <li>Gurukula Mandir Vidya Peeta</li>
        <li>Sarkari Hiriya Prathamika Shaale</li>
        <li>Narachi Vidya mandir</li>
    </ol>
</body>
</html>